services:
  stun:
    build: ./stun/.
    ports:
      - "3478:3478"
    depends_on:
      - signaling

  signaling:
    build: ./signaling/.
    ports:
      - "3000:3000"
    environment:
      TZ: "Asia/Tokyo"
