apiVersion: v1
kind: Service
metadata:
  name: coturn-stun-server
spec:
  type: LoadBalancer
  ports:
    - port: 3478
      targetPort: 3478
      protocol: UDP
      name: udp
    - port: 3478
      targetPort: 3478
      protocol: TCP
      name: tcp
  selector:
    app: coturn-stun-server