apiVersion: apps/v1
kind: Deployment
metadata:
  name: coturn-stun-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coturn-stun-server
  template:
    metadata:
      labels:
        app: coturn-stun-server
    spec:
      containers:
      - name: coturn-stun-server
        image: gcr.io/unicorn-hal/coturn-stun-server:latest
        ports:
        - containerPort: 3478
          protocol: UDP
        - containerPort: 3478
          protocol: TCP
        args:
          - turnserver
          - "-n"
          - "--log-file=stdout"
          - "--min-port=49160"
          - "--max-port=49200"
          - "--no-tls"
          - "--no-dtls"
          - "--listening-port=3478"
          - "--realm=example.com"
